name: Uclid CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Z3
      id: cache-z3
      uses: actions/cache@v1
      with:
        path: z3/
        key: ${{ runner.os }}-z3-${{ hashFiles('get-z3-linux.sh') }}-1

    - name: Download Z3
      if: steps.cache-z3.outputs.cache-hit != 'true'
      run: ./get-z3-linux.sh
       
    - name: Add Z3 to Path
      run: |
       ls $GITHUB_WORKSPACE/z3/bin/
       echo "::add-path::$GITHUB_WORKSPACE/z3/bin/"
       echo "::set-env name=LD_LIBRARY_PATH::$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/z3/bin/"

    - name: Print Z3 Version
      run: z3 --version

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Compile
      run: sbt compile

    - name: Test
      run: sbt "set fork:=true" test

    - name: Package
      run: sbt universal:packageBin

  test-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: openjdk@1.11

    - name: Install Z3
      run: |
        git clone https://github.com/Z3Prover/z3.git
        cd z3
        python scripts/mk_make.py --java
        cd build
        make -j4
        sudo make install
        cd ../..

    - name: Print Z3 Version
      run: z3 --version

    - name: Copy the Z3 java libraries
      run: |
        sudo cp $GITHUB_WORKSPACE/z3/build/libz3java.dylib /Library/Java/Extensions/
        sudo cp $GITHUB_WORKSPACE/z3/build/libz3.dylib /usr/local/lib/     

    - name: Compile
      run: sbt compile

    - name: Test UCLID
      run: sbt "set fork:=true" test

    - name: Package UCLID
      run: sbt universal:packageBin
